### ISSUE TITLE
Error in admin

### ISSUE THREAD

**Issue by fschroiff** [mentosmenno2/image-crop-positioner#33]
In wp-admin I get the following:

```
Refused to load the image 'http://foo.bar/wp-content/uploads/2021/12/cropped-favicon-150x150.png?image-crop-positioner-ts=1638788645' because it violates the following Content Security Policy directive: "img-src data: https: blob: android-webview android-webview-video-poster:".
```

macOS 12.0.1 / Chrome 96.0.4664.110

**Comment by mentosmenno2** [comment]
This is an issue with your hosting setup in combination with your wordpress installation.
Your WP installation is running on http, while your hosting setup (specifically the Content Security Policy) requires you to use https.
You should be able to solve this by or allowing http in your nginx, or changing the home url of your WordPress installation to use https.
