### ISSUE TITLE
Conflict with download monitor

### ISSUE THREAD

**Issue by menno-ll** [mentosmenno2/image-crop-positioner#37]
Download monitor urls won't work because the url parameter for breaking cache is added.

For example: https://www.ondernemen010.nl/wp-content/uploads/dlm_uploads/2022/02/kaart-terrasschermen-3.jpg?image-crop-positioner-ts=1645622612

A quickfix could be to add an option to disable the url paramter.
This would however result in images beeing cached, and the new cropped version not beeing shown.

But the actual problem is that download monitor does not allow using url paramters in its urls. Thats the main problem that should be solved and/or bypassed.

**Comment by mentosmenno2** [comment]
I've attempted the steps below to reproduce the issue:

- Install download monitor plugin
- Create a download, referencing a file from the media library
- Place a download button for this file on an example page

Using these steps, i was not able to reproduce this issue.
Please provide extra steps required to reproduce the issue.

For now, as a workaround, i've added a feature request to disable the cache breaker parameter. However, this might cause issues with caching on some server configurations. This feature won't have the highest priority.
https://github.com/mentosmenno2/image-crop-positioner/issues/38

**Comment by nlcruise** [comment]
Here are specific steps to reproduce the issue:

1. Install download manager plugin
2. Upload a JPEG file via the WordPress media library (only tested with *.jpg, not with *.jpeg)
3. Create a download in the Download Manager plugin and reference the JPEG file from step 2 as download
4. Save the download
5. Copy the link shown in a side widget called 'Download info'
6. Navigate to the copied link

Result; HTTP 200, but reported as invalid response so the browser does not load any response data.

**Comment by mentosmenno2** [comment]
Hi @nlcruise ,

By following your steps I was able to reproduce this issue.
It occured because the plugin replaced the original atachment url, but it should only replace the image source.
The issue is resolved in #39 .

Also i've added a feature to disable cache breaking in #41 .

Your changes will be included in the next version [v0.2.0](https://github.com/mentosmenno2/image-crop-positioner/releases/tag/v0.2.0) of the plugin.
This will be released after Github Actions has fixed its downtime.

**Comment by mentosmenno2** [comment]
Hi @nlcruise ,

I can confirm [v0.2.0](https://github.com/mentosmenno2/image-crop-positioner/releases/tag/v0.2.0) has been released and should be available via packagist soon.
