### ISSUE TITLE
Javascript face detection with CDN not working

### ISSUE THREAD

**Issue by menno-ll** [mentosmenno2/image-crop-positioner#43]
When an image is hosted on a CDN with a different url (even with a different subdomain), javascript image recognition will fail with the following message:
"JavaScript faces detection failed for this picture."

**Comment by menno-ll** [comment]
This might do the trick.

```js
				const imageElement = getPreviewImage();
				const canvas = document.createElement( 'canvas' );
				const ctx = canvas.getContext( '2d' );
				canvas.height = imageElement[ 0 ].naturalHeight;
				canvas.width = imageElement[ 0 ].naturalWidth;
				ctx.drawImage( imageElement[ 0 ], 0, 0 );
				
				$(canvas).faceDetection();
```

**Comment by mentosmenno2** [comment]
Nope that does not work:
DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.

What needs to be done is to download the image via php, and convert it to a format that can be set as image source as raw data.
Then that image can be used for the face detection
